### ISSUE TITLE
Investigate firing upstream `ThanosReceiveNoUpload` alert

### ISSUE THREAD

**Issue by bastjan** [projectsyn/component-thanos#30]
`ThanosReceiveNoUpload` seems to be firing on all appuio-cloud clusters.

From what I can see the alert triggers on the standby instance, since only the active instance uploads blocks.

Either the upstream alert is wrong and should ignore the standby instance or we don't configure standby instances correctly.

I've workaround the firing alert by only alerting if all instances show no uploads in the last three hours. [INTERNAL](https://git.vshn.net/syn/commodore-defaults/-/commit/2c7c9aa07c70037dfcb2d7167ce88152989ce431)

```yaml
    receive_alerts:
      patches:
        ThanosReceiveNoUpload:
          expr: max by(job) ( (up{job=~".*thanos-receive.*"} - 1) + on(job, instance) (sum by(job, instance) (increase(thanos_shipper_uploads_total{job=~".*thanos-receive.*"}[3h]))) ) == 0
```

## Steps to Reproduce the Problem

  1. Install this component with `receive: { enabled: true }`
  2. Wait for alert to fire.
  

## Actual Behavior

`ThanosReceiveNoUpload` firing even though the active instance uploads blocks.

## Expected Behavior

`ThanosReceiveNoUpload` only firing when no blocks are uploaded.
